import { MigrationInterface, QueryRunner } from "typeorm";

export class AddIsPremiereToProgramTable1780960227836 implements MigrationInterface {
    name = 'AddIsPremiereToProgramTable1780960227836'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_8e94f9ea563e95f6b0acd43e2d1"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_push_subscriptions_device"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "FK_devices_user"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "FK_user_subscriptions_program"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "FK_user_subscriptions_user"`);
        await queryRunner.query(`ALTER TABLE "channel_categories_category" DROP CONSTRAINT "FK_bcba63102e52c76d6bc4e73e0d6"`);
        await queryRunner.query(`ALTER TABLE "channel_categories_category" DROP CONSTRAINT "FK_f24cf0ebff30027213fdc6db9ae"`);
        await queryRunner.query(`ALTER TABLE "streamer_categories_category" DROP CONSTRAINT "fk_scc_category"`);
        await queryRunner.query(`ALTER TABLE "streamer_categories_category" DROP CONSTRAINT "fk_scc_streamer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_schedule_day_time_visible"`);
        await queryRunner.query(`DROP INDEX "public"."idx_program_channel_live"`);
        await queryRunner.query(`DROP INDEX "public"."idx_channel_visible_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_device_device_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_subscription_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_streamer_is_visible"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_streamer_is_visible_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_streamer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_streamer_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_origin"`);
        await queryRunner.query(`DROP INDEX "public"."idx_banner_is_enabled"`);
        await queryRunner.query(`DROP INDEX "public"."idx_banner_display_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_banner_dates"`);
        await queryRunner.query(`DROP INDEX "public"."idx_banner_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_banner_is_fixed"`);
        await queryRunner.query(`DROP INDEX "public"."idx_banner_priority"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "UQ_push_subscriptions_device_endpoint"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "UQ_user_program"`);
        await queryRunner.query(`ALTER TABLE "program" ADD "is_premiere" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP COLUMN "start_time"`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD "start_time" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP COLUMN "end_time"`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD "end_time" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedule" ALTER COLUMN "program_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "category" ADD "color" text`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ALTER COLUMN "endpoint" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "devices"."platform" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "devices"."fcm_token" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "devices"."app_version" IS NULL`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" DROP CONSTRAINT "FK_db9c663eaafbb6b11bf1ab21643"`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" DROP CONSTRAINT "FK_4c6cd49f38a97897d083d3f19dd"`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" ALTER COLUMN "streamer_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."link_type_enum" RENAME TO "link_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."banner_link_type_enum" AS ENUM('internal', 'external', 'none')`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "link_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "link_type" TYPE "public"."banner_link_type_enum" USING "link_type"::"text"::"public"."banner_link_type_enum"`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "link_type" SET DEFAULT 'none'`);
        await queryRunner.query(`DROP TYPE "public"."link_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "is_fixed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "priority" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."banner_type_enum" RENAME TO "banner_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."banner_banner_type_enum" AS ENUM('news', 'promotional', 'featured')`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "banner_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "banner_type" TYPE "public"."banner_banner_type_enum" USING "banner_type"::"text"::"public"."banner_banner_type_enum"`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "banner_type" SET DEFAULT 'news'`);
        await queryRunner.query(`DROP TYPE "public"."banner_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_52f1901a14df9cf9f289e14c44" ON "schedule" ("start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e94f9ea563e95f6b0acd43e2d" ON "schedule" ("program_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a48dad7d0c2eb14c2abae4786" ON "schedule" ("day_of_week", "start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_87bbf82a85ef121d71072ff194" ON "channel" ("is_visible", "order") `);
        await queryRunner.query(`CREATE INDEX "IDX_78604ebe676945b7754f5dab29" ON "streamer" ("is_visible", "order") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e5dd463d799a31ca5d42eb432" ON "user_streamer_subscriptions" ("streamer_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_75658a707cd54fe2bca1e1e4d7" ON "banner" ("banner_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb41990f3657bcac48e20214b1" ON "banner" ("start_date", "end_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_657ecc7f424d30ef90187d3964" ON "banner" ("display_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_659ec9fe147ec5cb5c793a902c" ON "banner" ("is_enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcba63102e52c76d6bc4e73e0d" ON "channel_categories_category" ("channelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f24cf0ebff30027213fdc6db9a" ON "channel_categories_category" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86f23e9d8520422d51e9237007" ON "streamer_categories_category" ("streamerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_508c70a04eb2615697574e2cd9" ON "streamer_categories_category" ("categoryId") `);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "UQ_30508b7e7b4679abc4a0b3b9519" UNIQUE ("device_id", "endpoint")`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "UQ_2ca1d74b47646c179db430fd266" UNIQUE ("user_id", "program_id")`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" ADD CONSTRAINT "UQ_6c9a24b77e2f4514c68c6b27158" UNIQUE ("user_id", "streamer_id")`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_8e94f9ea563e95f6b0acd43e2d1" FOREIGN KEY ("program_id") REFERENCES "program"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_c3b311df04881936281c0273450" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "FK_5e9bee993b4ce35c3606cda194c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "FK_0641da02314913e28f6131310eb" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "FK_9423a8ac8f1bd798d276303db7c" FOREIGN KEY ("program_id") REFERENCES "program"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" ADD CONSTRAINT "FK_db9c663eaafbb6b11bf1ab21643" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" ADD CONSTRAINT "FK_4c6cd49f38a97897d083d3f19dd" FOREIGN KEY ("streamer_id") REFERENCES "streamer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel_categories_category" ADD CONSTRAINT "FK_bcba63102e52c76d6bc4e73e0d6" FOREIGN KEY ("channelId") REFERENCES "channel"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channel_categories_category" ADD CONSTRAINT "FK_f24cf0ebff30027213fdc6db9ae" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "streamer_categories_category" ADD CONSTRAINT "FK_86f23e9d8520422d51e92370073" FOREIGN KEY ("streamerId") REFERENCES "streamer"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "streamer_categories_category" ADD CONSTRAINT "FK_508c70a04eb2615697574e2cd92" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "streamer_categories_category" DROP CONSTRAINT "FK_508c70a04eb2615697574e2cd92"`);
        await queryRunner.query(`ALTER TABLE "streamer_categories_category" DROP CONSTRAINT "FK_86f23e9d8520422d51e92370073"`);
        await queryRunner.query(`ALTER TABLE "channel_categories_category" DROP CONSTRAINT "FK_f24cf0ebff30027213fdc6db9ae"`);
        await queryRunner.query(`ALTER TABLE "channel_categories_category" DROP CONSTRAINT "FK_bcba63102e52c76d6bc4e73e0d6"`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" DROP CONSTRAINT "FK_4c6cd49f38a97897d083d3f19dd"`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" DROP CONSTRAINT "FK_db9c663eaafbb6b11bf1ab21643"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "FK_9423a8ac8f1bd798d276303db7c"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "FK_0641da02314913e28f6131310eb"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "FK_5e9bee993b4ce35c3606cda194c"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_c3b311df04881936281c0273450"`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_8e94f9ea563e95f6b0acd43e2d1"`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" DROP CONSTRAINT "UQ_6c9a24b77e2f4514c68c6b27158"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "UQ_2ca1d74b47646c179db430fd266"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "UQ_30508b7e7b4679abc4a0b3b9519"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_508c70a04eb2615697574e2cd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86f23e9d8520422d51e9237007"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f24cf0ebff30027213fdc6db9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcba63102e52c76d6bc4e73e0d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_659ec9fe147ec5cb5c793a902c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_657ecc7f424d30ef90187d3964"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb41990f3657bcac48e20214b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75658a707cd54fe2bca1e1e4d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e5dd463d799a31ca5d42eb432"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78604ebe676945b7754f5dab29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87bbf82a85ef121d71072ff194"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a48dad7d0c2eb14c2abae4786"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e94f9ea563e95f6b0acd43e2d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52f1901a14df9cf9f289e14c44"`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."banner_type_enum_old" AS ENUM('news', 'promotional', 'featured')`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "banner_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "banner_type" TYPE "public"."banner_type_enum_old" USING "banner_type"::"text"::"public"."banner_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "banner_type" SET DEFAULT 'news'`);
        await queryRunner.query(`DROP TYPE "public"."banner_banner_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."banner_type_enum_old" RENAME TO "banner_type_enum"`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "priority" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "is_fixed" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."link_type_enum_old" AS ENUM('internal', 'external', 'none')`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "link_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "link_type" TYPE "public"."link_type_enum_old" USING "link_type"::"text"::"public"."link_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "link_type" SET DEFAULT 'none'`);
        await queryRunner.query(`DROP TYPE "public"."banner_link_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."link_type_enum_old" RENAME TO "link_type_enum"`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" ALTER COLUMN "streamer_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" ADD CONSTRAINT "FK_4c6cd49f38a97897d083d3f19dd" FOREIGN KEY ("streamer_id") REFERENCES "streamer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_streamer_subscriptions" ADD CONSTRAINT "FK_db9c663eaafbb6b11bf1ab21643" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "devices"."app_version" IS 'Application version number'`);
        await queryRunner.query(`COMMENT ON COLUMN "devices"."fcm_token" IS 'Firebase Cloud Messaging token for push notifications'`);
        await queryRunner.query(`COMMENT ON COLUMN "devices"."platform" IS 'Platform type: ios, android, or web'`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ALTER COLUMN "endpoint" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "category" ADD "color" character varying`);
        await queryRunner.query(`ALTER TABLE "schedule" ALTER COLUMN "program_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP COLUMN "end_time"`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD "end_time" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP COLUMN "start_time"`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD "start_time" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "program" DROP COLUMN "is_premiere"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "UQ_user_program" UNIQUE ("user_id", "program_id")`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "UQ_push_subscriptions_device_endpoint" UNIQUE ("endpoint", "device_id")`);
        await queryRunner.query(`CREATE INDEX "idx_banner_priority" ON "banner" ("priority") `);
        await queryRunner.query(`CREATE INDEX "idx_banner_is_fixed" ON "banner" ("is_fixed") `);
        await queryRunner.query(`CREATE INDEX "idx_banner_type" ON "banner" ("banner_type") `);
        await queryRunner.query(`CREATE INDEX "idx_banner_dates" ON "banner" ("start_date", "end_date") `);
        await queryRunner.query(`CREATE INDEX "idx_banner_display_order" ON "banner" ("display_order") `);
        await queryRunner.query(`CREATE INDEX "idx_banner_is_enabled" ON "banner" ("is_enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_origin" ON "users" ("origin") `);
        await queryRunner.query(`CREATE INDEX "IDX_streamer_active" ON "user_streamer_subscriptions" ("streamer_id", "is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_user_streamer" ON "user_streamer_subscriptions" ("user_id", "streamer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_streamer_is_visible_order" ON "streamer" ("is_visible", "order") `);
        await queryRunner.query(`CREATE INDEX "IDX_streamer_is_visible" ON "streamer" ("is_visible") `);
        await queryRunner.query(`CREATE INDEX "idx_user_subscription_active" ON "user_subscriptions" ("is_active", "user_id") WHERE (is_active = true)`);
        await queryRunner.query(`CREATE INDEX "idx_device_device_id" ON "devices" ("device_id") `);
        await queryRunner.query(`CREATE INDEX "idx_channel_visible_order" ON "channel" ("order", "is_visible") WHERE (is_visible = true)`);
        await queryRunner.query(`CREATE INDEX "idx_program_channel_live" ON "program" ("channel_id", "is_live") WHERE (channel_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_schedule_day_time_visible" ON "schedule" ("day_of_week", "start_time") WHERE (day_of_week IS NOT NULL)`);
        await queryRunner.query(`ALTER TABLE "streamer_categories_category" ADD CONSTRAINT "fk_scc_streamer" FOREIGN KEY ("streamerId") REFERENCES "streamer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "streamer_categories_category" ADD CONSTRAINT "fk_scc_category" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel_categories_category" ADD CONSTRAINT "FK_f24cf0ebff30027213fdc6db9ae" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel_categories_category" ADD CONSTRAINT "FK_bcba63102e52c76d6bc4e73e0d6" FOREIGN KEY ("channelId") REFERENCES "channel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "FK_user_subscriptions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "FK_user_subscriptions_program" FOREIGN KEY ("program_id") REFERENCES "program"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "FK_devices_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_push_subscriptions_device" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_8e94f9ea563e95f6b0acd43e2d1" FOREIGN KEY ("program_id") REFERENCES "program"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
