name: Check CHANGELOG update

on:
  pull_request:
    branches: [main, develop]

jobs:
  changelog-check:
    runs-on: ubuntu-latest
    name: Verificar que se haya modificado el CHANGELOG
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
      
      - name: Fetch all branches
        run: git fetch --all

      - name: Obtener archivos modificados
        id: files
        run: |
          base_ref="$(git merge-base origin/${{ github.base_ref }} HEAD || echo 'no-merge-base')"
          if [ "$base_ref" = "no-merge-base" ]; then
            echo "No common base found between branches"
            exit 1
          fi
          echo "changed=$(git diff --name-only $base_ref...HEAD)" >> $GITHUB_OUTPUT

      - name: Verificar si se modificó CHANGELOG.md
        run: |
          echo "${{ steps.files.outputs.changed }}" | grep -q "CHANGELOG.md" || (echo "❌ No se modificó CHANGELOG.md" && exit 1)